### ISSUE TITLE
代码请教

### ISSUE THREAD

**Issue by MiracloveLe** [Codennnn/Apifox-UI#1]
你好，大佬，我是一位初学者。看到您这个项目之后想down下来学习一下。奈何代码过于高深，看不太懂，所以斗胆来问一下大佬这一块什么时候开发，或者是用什么技术开发。
![image](https://github.com/Codennnn/Apifox-UI/assets/143673018/5a0f1a27-df80-42e4-b9a0-bcd1da30ba48)

**Comment by MiracloveLe** [comment]
就是这一块富文本和代码块回显

**Comment by Codennnn** [comment]
这一块的功能计划在本周内完成。

在项目整体模块开发完后，我会对代码结构进行梳理，并对其中难以理解的代码段进行注释，以便于初学者阅读和理解，请稍作等待。
