### ISSUE TITLE
保存功能会报错

### ISSUE THREAD

**Issue by codelzb** [Codennnn/Apifox-UI#10]
修改任意一个接口文档， 在返回响应中添加一条新响应， 点击保存后会出现如图错误；
 我想原因应该是onFinish回调只会返回items绑定了name的值，  而responseExamples字段的id并没有绑定所以获取不到；这样进行保存，再次渲染会导致错误。 这个[issues](https://github.com/Codennnn/Apifox-UI/issues/8)应该也是同样的原因，  我正在学习react，不知是否可以改为form.getFieldsValue(true)来获取表单所有值再进行保存呢 @Codennnn 
![image](https://github.com/user-attachments/assets/957c3b5b-4809-4df5-b7b0-7187c35068be)

**Comment by Codennnn** [comment]
这个问题修复好了👌
