### ISSUE TITLE
JSON Schema类型编辑时，节点类型为array时，Item不渲染问题

### ISSUE THREAD

**Issue by dragonzhao93** [Codennnn/Apifox-UI#5]
![image](https://github.com/user-attachments/assets/22e6511d-4265-41a8-bce7-963fab1ef558)

**Comment by Codennnn** [comment]
修复好了，把「展开箭头」去掉了，array 是没有 item 的。

**Comment by dragonzhao93** [comment]
问题好像还是存在，在根节点使用array，子节点Item选择Object的时候无法添加object的子节点。
另外感谢作者的开源，学习了很多。

**Comment by Codennnn** [comment]
这个组件的确缺失了这些功能，稍等我补上去🫡

**Comment by Codennnn** [comment]
这个问题已经修复了！
