### ISSUE TITLE
Apifox-UI可以支持next静态导出吗

### ISSUE THREAD

**Issue by codelzb** [Codennnn/Apifox-UI#7]
如果可以的话, 想请问下该如何做 @Codennnn    我根据[next文档](https://nextjs.org/docs/app/building-your-application/deploying/static-exports)操作好像页面会无法访问

**Comment by Codennnn** [comment]
遵循以下步骤，你就可以通过 http://127.0.0.1:8080 在本地访问静态文件：
1. 在 `next.config.mjg` 中增加配置 `output: 'export'`。
2. 执行 `npm run build` 构建出 `out` 目录。
3. 使用 npm 安装 `http-server`，成功后在项目根目录上运行命令 `http-server ./out`。

**Comment by codelzb** [comment]
@Codennnn 感谢 完美的成功了
