### ISSUE TITLE
在开发环境中新建快捷请求出现了报错

### ISSUE THREAD

**Issue by codelzb** [Codennnn/Apifox-UI#8]
复现步骤：
1. pnpm dev
2. 新建快捷请求
3. 在输入框内随意填写一串url
4. 点击保存
5. 就会出现如图控制台中的报错
@Codennnn 
如果是运行打包后的html就不会出现这个报错
![image](https://github.com/user-attachments/assets/cad8b829-1a4e-488d-b900-4deb2a337503)

**Comment by Codennnn** [comment]
修复好了，再试试。

**Comment by codelzb** [comment]
> 修复好了，再试试。

依然能够复现,这个问题只会出现一次  多次点击就不会出现了
复现步骤  刷新浏览器   输入url  首次点击保存按钮 @Codennnn

**Comment by Codennnn** [comment]
我发了最新一版，好像没这个错误了，你再试试。
