### ISSUE TITLE
如何实现左侧面板的宽度，不受浏览器的宽度调整变化

### ISSUE THREAD

**Issue by TestCabana** [Codennnn/Apifox-UI#9]
左侧面板的宽度，不受浏览器的宽度调整变化，
![image](https://github.com/user-attachments/assets/fa37f14e-9e2f-4532-912c-ed9e543b9bb1)

**Comment by Lrunlin** [comment]
固定长度使用PX单位不就可以嘛

**Comment by Codennnn** [comment]
现在拖动时会固定侧边栏的宽度了。

**Comment by TestCabana** [comment]
没法实现，左侧面板是支持拖动把手调整宽度，



在 2024-08-30 20:05:46，"Run Lin" ***@***.***> 写道：

固定长度使用PX单位不就可以嘛
